fileversion: 3

robots:
  cf5:
    enabled: true
    uri: radio://1/40/2M/E7E7E7E705
    initial_position: [0.707, 0.707, 0.08]
    type: cf_vicon
  cf6:
    enabled: true
    uri: radio://7/50/2M/E7E7E7E706
    initial_position: [1.0, 0.0, 0.08]
    type: cf_vicon
  cf7:
    enabled: true
    uri: radio://2/60/2M/E7E7E7E707
    initial_position: [0.707, -0.707, 0.08]
    type: cf_vicon
  cf8:
    enabled: true
    uri: radio://0/70/2M/E7E7E7E708
    initial_position: [0.0, -1.0, 0.08]
    type: cf_vicon

robot_types:
  cf_vicon:
    motion_capture:
      tracking: "vendor"
    big_quad: false
    battery:
      voltage_warning: 3.8
      voltage_critical: 3.7

all:
  firmware_logging:
    enabled: true
    default_topics:
      pose:
        frequency: 10
      status:
        frequency: 1
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2
      controller: 1
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 5e-2
  reference_frame: "world"
  broadcasts:
    num_repeats: 15
    delay_between_repeats_ms: 1
