/motion_capture_tracking:
  ros__parameters:
    type: "vicon"
    hostname: "10.192.46.131"

    topics:
      frame_id: "world"
      poses:
        qos:
          mode: "sensor"
          deadline: 100.0
      tf:
        child_frame_id: "{}"

